[libraries]
apache-commons-io = { module = "commons-io:commons-io", version = "2.11.0" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version = "1.1.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.22.0" }
